## Aula 01

In [56]:
#Importando a base de dados 
import pandas as pd 

dados_churn = pd.read_json("arquivo.json")
dados_churn.head()

,id_cliente,Churn,cliente,telefone,internet,conta
0,0002-ORFBO,nao,"{'genero': 'feminino', 'idoso': 0, 'parceiro':...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'DSL', 'seguranca_online'...","{'contrato': None, 'faturamente_eletronico': N..."
1,0003-MKNFE,nao,"{'genero': 'masculino', 'idoso': 0, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'DSL', 'seguranca_online'...","{'contrato': 'mes a mes', 'faturamente_eletron..."
2,0004-TLHLJ,sim,"{'genero': 'masculino', 'idoso': 0, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."
3,0011-IGKFF,sim,"{'genero': 'masculino', 'idoso': 1, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."
4,0013-EXCHZ,sim,"{'genero': 'feminino', 'idoso': 1, 'parceiro':...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."

In [57]:
#Normalizando todas colunas de uma vez
import json 

with open ('arquivo.json') as d:
    json_bruto = json.load(d)

dados_normalizado = pd.json_normalize(json_bruto)
dados_normalizado.head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0002-ORFBO,nao,feminino,0,sim,sim,9.0,sim,nao,DSL,...,sim,nao,sim,sim,nao,None,None,None,NaN,None
1,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.9,542.4
2,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.9,280.85
3,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.0,1237.85
4,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.9,267.4

In [58]:
dados_normalizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7344 entries, 0 to 7343
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_cliente                     7344 non-null   object
 1   Churn                          7344 non-null   object
 2   cliente.genero                 7344 non-null   object
 3   cliente.idoso                  7344 non-null   int64
 4   cliente.parceiro               7344 non-null   object
 5   cliente.dependentes            7344 non-null   object
 6   cliente.tempo_servico          7336 non-null   float64
 7   telefone.servico_telefone      7344 non-null   object
 8   telefone.varias_linhas         7344 non-null   object
 9   internet.servico_internet      7344 non-null   object
 10  internet.seguranca_online      7344 non-null   object
 11  internet.backup_online         7344 non-null   object
 12  internet.protecao_dispositivo  7344 non-null   object
 13  internet.suporte_tecnico       7344 non-null   object
 14  internet.tv_streaming          7344 non-null   object
 15  internet.filmes_streaming      7344 non-null   object
 16  conta.contrato                 7312 non-null   object
 17  conta.faturamente_eletronico   7326 non-null   object
 18  conta.metodo_pagamento         7317 non-null   object
 19  conta.cobranca.mensal          7326 non-null   float64
 20  conta.cobranca.Total           7328 non-null   object
dtypes: float64(2), int64(1), object(18)
memory usage: 1.2+ MB

In [59]:
# Alterando o tipo da coluna 'conta.cobranca.Total' para 'float64'

dados_normalizado['conta.cobranca.Total']

0          None
1         542.4
2        280.85
3       1237.85
4         267.4
         ...
7339       7875
7340     620.55
7341    3019.25
7342      798.2
7343      278.4
Name: conta.cobranca.Total, Length: 7344, dtype: object